### ISSUE TITLE
SSR not working, html source just shows the loading...

### ISSUE THREAD

**Issue by romanianni** [fazlulkarimweb/with-next-redux-wrapper-redux-persist#8]
Hi! i found this boilerplate facing the same issue that a lot of people has. This wrapper works but SSR its not working, there is a workaround with this issue? Thanks in advance!

**Comment by samipshah100** [comment]
@ramtis i am wondering if we need to to do this https://github.com/kirill-konshin/next-redux-wrapper#server-and-client-state-separation

**Comment by fazlulkarimweb** [comment]
I have attached SSR example in my code under the SSR folder. It works perfectly from my end without any problem. Please see this example - https://github.com/fazlulkarimweb/with-next-redux-wrapper-redux-persist/blob/master/pages/ssr/index.js 

Did this piece of the aforementioned code run on your computer perfectly? It works on my computer perfectly.

**Comment by trangchongcheng** [comment]
I has build you example, but i see it only show loading... @fazlulkarimweb , 
<img width="1780" alt="Screen Shot 2021-10-18 at 17 41 56" src="https://user-images.githubusercontent.com/9212168/137716251-f346a042-a4cb-4692-9e63-aa4b1a3c0891.png">

**Comment by trangchongcheng** [comment]
> Hi! i found this boilerplate facing the same issue that a lot of people has. This wrapper works but SSR its not working, there is a workaround with this issue? Thanks in advance!

Are you fixed? I have same isue

**Comment by fazlulkarimweb** [comment]
@trangchongcheng I have given a complete update of this boilerplate. These issues probably emerged from the very old packages and redux-persists new updates. I have changed the redux-persists storage method. Please, pull the current repo (updated a few minutes ago) repo and see if the problem is solved. Please, let me know again if the same problem persists. I will try my best to solve the issue.

**Comment by trangchongcheng** [comment]
> @trangchongcheng I have given a complete update of this boilerplate. These issues probably emerged from the very old packages and redux-persists new updates. I have changed the redux-persists storage method. Please, pull the current repo (updated a few minutes ago) repo and see if the problem is solved. Please, let me know again if the same problem persists. I will try my best to solve the issue.

Thank for reply.
I have pull new source but when i building, it still above issue...Many peopel have same isue, like this:
https://github.com/vercel/next.js/issues/8240


<img width="1737" alt="Screen Shot 2021-10-21 at 15 45 55" src="https://user-images.githubusercontent.com/9212168/138249639-e3d6cd50-0659-4cf7-a935-c4f28e9827af.png">

**Comment by fazlulkarimweb** [comment]
Change your app.js to this and let me know. 

```js
import App from 'next/app';
import { wrapper } from '../store/store';
import { useStore } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';

function MyApp({ Component, pageProps }) {
  const store = useStore((state) => state);
  return process.browser ? (
    <PersistGate persistor={store.__persistor} loading={<div>Loading</div>}>
      <Component {...pageProps} />
    </PersistGate>
  ) : (
    <PersistGate persistor={store}>
      <Component {...pageProps} />
    </PersistGate>
  );
}

export default wrapper.withRedux(MyApp);
```

**Comment by fazlulkarimweb** [comment]
I have taken this code snippet from the official Next js website. There is no store or any other dependency. You can create a page in your Next js folder. Then run the npm run build and see the result. Then you will understand what is the expected code in the previous redux-based solution. I see similar results. I think it will help you understand the expected result.

```js
import React from 'react';
import axios from 'axios';

function Users({ posts }) {
  return (
    <ul>
      {posts.map((post) => (
        <li>{post.title}</li>
      ))}
    </ul>
  );
}

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries. See the "Technical details" section.
export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://jsonplaceholder.typicode.com/posts');
  const posts = await res.json();

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      posts,
    },
  };
}

export default Users;
```

**Comment by trangchongcheng** [comment]
I using like below, it working but it maybe not best practice because it throw warning`Warning: Did not expect server HTML to contain a <div> in <div>`

```
const MyApp = ({ Component, pageProps }: Props) => {
  const store: StoreType = useStore();

  const getLayout =
    Component.getLayout ||
    ((page: ReactNode) => <SiteLayout isFull={false}>{page}</SiteLayout>);

  const app = (
    <Chakra>
      <AppContextProvider>
          <PostContextProvider>
            {getLayout(<Component {...pageProps} />)}
          </PostContextProvider>
      </AppContextProvider>
    </Chakra>
  );
  if (typeof window !== 'undefined') {
    return (
      <PersistGate persistor={store.__PERSISTOR as Persistor} loading={null}>
        {app}
      </PersistGate>
    );
  } else {
    return app;
  }
```
So many topic about this issue:
https://github.com/rt2zz/redux-persist/issues/926
https://github.com/vercel/next.js/issues/8240#issuecomment-647699316
https://stackoverflow.com/questions/58238525/gatsby-not-generating-correct-static-html-files/62501513#62501513

**Comment by trangchongcheng** [comment]
> I have taken this code snippet from the official Next js website. There is no store or any other dependency. You can create a page in your Next js folder. Then run the npm run build and see the result. Then you will understand what is the expected code in the previous redux-based solution. I see similar results. I think it will help you understand the expected result.

If not using redux-persist, you can see when we use npm run build then static HTML will render between <div id="__next"> </div>

**Comment by simplenotezy** [comment]
@fazlulkarimweb Actually this issue ought to be opened. I have the same issue, and I followed your practice step-by-step, from the readme here: https://github.com/fazlulkarimweb/with-next-redux-wrapper-redux-persist

It is working, but if you disable javascript in the browser, you'll see a white screen, or whatever you provided to `loading={}` prop on PersistGate.

![image](https://user-images.githubusercontent.com/3786627/144127921-95f43f2e-6e7c-4c39-8157-ee8956d4d838.png)

Also I notice your current repo differs from your readme file: https://github.com/fazlulkarimweb/with-next-redux-wrapper-redux-persist/blob/master/pages/_app.js

Is the readme up to date?

**Comment by fazlulkarimweb** [comment]
> @fazlulkarimweb Actually this issue ought to be opened. I have the same issue, and I followed your practice step-by-step, from the readme here: https://github.com/fazlulkarimweb/with-next-redux-wrapper-redux-persist
> 
> It is working, but if you disable javascript in the browser, you'll see a white screen, or whatever you provided to `loading={}` prop on PersistGate.
> 
> ![image](https://user-images.githubusercontent.com/3786627/144127921-95f43f2e-6e7c-4c39-8157-ee8956d4d838.png)
> 
> Also I notice your current repo differs from your readme file: https://github.com/fazlulkarimweb/with-next-redux-wrapper-redux-persist/blob/master/pages/_app.js
> 
> Is the readme up to date?

[Issues #22 ](https://github.com/fazlulkarimweb/with-next-redux-wrapper-redux-persist/issues/22 ) - I have explained this in detail here now. Let's discuss the issues there instead.
