### ISSUE TITLE
Add redux toolkit example

### ISSUE THREAD

**Issue by MaciejWiatr** [fazlulkarimweb/with-next-redux-wrapper-redux-persist#9]
I think that adding redux toolkit example on the separate branch would be great
link to example:
https://github.com/samipshah100/with-next-redux-wrapper-redux-persist/blob/master/README.md

**Comment by fazlulkarimweb** [comment]
Thanks for the info. Currently, I'm developing a boilerplate which is independent of the next-redux-wrapper but with similar functionality. I will release that shortly. I will use the redux toolkit there.

**Comment by MaciejWiatr** [comment]
@fazlulkarimweb Nice, can't wait to see it :)
And also could you keep in mind that persist is messing SSR, I've got around this problem by using <Component> inside PersistGate however it is a really silly solution and if you'd be able to come up with a better one I'd love to see it also :)

**Comment by samipshah100** [comment]
great!
